<?php

namespace Moccalotto\Crypto;

use RuntimeException;

class Bytes
{
    /**
     * Get a number of securely generated bytes of data.
     *
     * @param int $count The number of bytes to get
     *
     * @return string
     */
    public static function random($count)
    {
        $result = openssl_random_pseudo_bytes($count, $secure);

        if (false === $result) {
            throw new RuntimeException('openssl_random_pseudo_bytes failed to generate random bytes');
        }

        if (false === $secure) {
            throw new RuntimeException('openssl_random_pseudo_bytes failed to generate secure randomness');
        }

        return $result;
    }

    /**
     * Count the number of bytes in a binary string
     *
     * @param string $str
     *
     * @return int
     */
    public static function count($str)
    {
        return mb_strlen($str, '8bit');
    }

    /**
     * Get a slice of a binary string
     *
     * @param string $str The binary string to slice
     * @param int $start The start position of the slice
     * @param int $length The length of the slice
     *
     * @return string
     */
    public static function slice($str, $start, $length = null)
    {
        return mb_substr($str, $start, $length, '8bit');
    }
}
